In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import extract
import random


# Define the logistic regression model
class LogisticRegression(nn.Module):
    def __init__(self):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(2, 1) 

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(2, 10)
        self.fc2 = nn.Linear(10, 3)

    def forward(self, x):
        x = F.relu(self.fc1(x))    # Pass input through first hidden layer and activation function
        x = self.fc2(x)
        #return torch.sigmoid(x)
        return F.softmax(x)

class NeuralNetwork2(nn.Module):
    def __init__(self):
        super(NeuralNetwork2, self).__init__()
        self.fc1 = nn.Linear(3, 10)
        self.fc2 = nn.Linear(10, 5)
        self.fc3 = nn.Linear(5, 4)

    def forward(self, x):
        x = F.relu(self.fc1(x))    # Pass input through first hidden layer and activation function# Output layer
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        #return torch.sigmoid(x)
        return F.softmax(x)

# Example usage:
# Create an instance of the NeuralNetwork class
#model = LogisticRegression()
model = NeuralNetwork()
print(model)


NeuralNetwork(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=3, bias=True)
)


In [3]:
#print(extract.get_tensor_from_mood_label("Angry"))

In [4]:
#print(extract.extract_features_from_uri("6mVD1SfTvlFAPVi7txFL5H"))

In [18]:
'''dataset = extract.extract_song_data("training_set.xlsx")

#print(dataset)
#print(len(dataset))



input_tensors = []
for i in range(0, len(dataset), 100):
    length = 100 if len(dataset) - i > 100 else len(dataset) - i
    uri_lst = [uri for _, uri, _ in dataset[i : i + length]]
    for t in extract.extract_features_from_uris(uri_lst):
        input_tensors.append(t)




inputs_outputs = [(input_tensors[i], extract.get_tensor_from_mood_label(dataset[i][2])) for i in range(dataset)]
training_set =random.sample(inputs_outputs, 300)
testing_set = [x for x in dataset if x not in training_set]


print(training_set[0:5])'''

dataset = extract.get_dataset_from_spreadsheet("final_tset.xlsx")
#print(dataset)

dataset = random.sample(dataset, len(dataset))
print(dataset)


[(tensor([0.6490, 0.6450]), tensor([1., 0., 0.])), (tensor([0.2970, 0.1850]), tensor([0., 0., 1.])), (tensor([0.9630, 0.2110]), tensor([0., 0., 1.])), (tensor([0.7240, 0.1500]), tensor([1., 0., 0.])), (tensor([0.5010, 0.3330]), tensor([0., 0., 1.])), (tensor([0.7150, 0.4970]), tensor([0., 1., 0.])), (tensor([0.9020, 0.3060]), tensor([0., 1., 0.])), (tensor([0.7100, 0.8450]), tensor([1., 0., 0.])), (tensor([0.8960, 0.5670]), tensor([1., 0., 0.])), (tensor([0.9440, 0.7350]), tensor([0., 1., 0.])), (tensor([0.4300, 0.1040]), tensor([0., 0., 1.])), (tensor([0.3760, 0.0723]), tensor([0., 0., 1.])), (tensor([0.4810, 0.0773]), tensor([0., 0., 1.])), (tensor([0.5210, 0.6790]), tensor([1., 0., 0.])), (tensor([0.7210, 0.5570]), tensor([1., 0., 0.])), (tensor([0.5750, 0.9640]), tensor([1., 0., 0.])), (tensor([0.7490, 0.6490]), tensor([1., 0., 0.])), (tensor([0.5320, 0.3670]), tensor([0., 0., 1.])), (tensor([0.6170, 0.5430]), tensor([1., 0., 0.])), (tensor([0.8530, 0.1190]), tensor([0., 0., 1.])),

In [19]:
#model = NeuralNetwork2()
model = NeuralNetwork()

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()

#criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
num_epochs = 200
for epoch in range(num_epochs):
    for x, y in dataset[0:300]:
        # Forward pass
        outputs = model(x)
        #print(outputs)
        #print(y)
        loss = criterion(outputs, y)
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    # Print loss for monitoring training progress
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

print('Training finished!')

C:\Users\Antti\AppData\Local\Temp\ipykernel_52420\2662789135.py:28: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(x)


Epoch [1/200], Loss: 1.1122
Epoch [2/200], Loss: 1.1720
Epoch [3/200], Loss: 1.2108
Epoch [4/200], Loss: 1.2286
Epoch [5/200], Loss: 1.2301
Epoch [6/200], Loss: 1.2200
Epoch [7/200], Loss: 1.2013
Epoch [8/200], Loss: 1.1751
Epoch [9/200], Loss: 1.1421
Epoch [10/200], Loss: 1.1028
Epoch [11/200], Loss: 1.0568
Epoch [12/200], Loss: 1.0060
Epoch [13/200], Loss: 0.9518
Epoch [14/200], Loss: 0.8979
Epoch [15/200], Loss: 0.8461
Epoch [16/200], Loss: 0.7997
Epoch [17/200], Loss: 0.7605
Epoch [18/200], Loss: 0.7271
Epoch [19/200], Loss: 0.7006
Epoch [20/200], Loss: 0.6786
Epoch [21/200], Loss: 0.6609
Epoch [22/200], Loss: 0.6466
Epoch [23/200], Loss: 0.6353
Epoch [24/200], Loss: 0.6261
Epoch [25/200], Loss: 0.6188
Epoch [26/200], Loss: 0.6128
Epoch [27/200], Loss: 0.6082
Epoch [28/200], Loss: 0.6044
Epoch [29/200], Loss: 0.6016
Epoch [30/200], Loss: 0.5995
Epoch [31/200], Loss: 0.5983
Epoch [32/200], Loss: 0.5978
Epoch [33/200], Loss: 0.5985
Epoch [34/200], Loss: 0.5998
Epoch [35/200], Loss: 0

In [20]:
#for x, y in dataset[300:]:
    #print(x)
    #print(y[1])
    #output = model(x)
    
    #print(str(y) + " | " + str(output))



#    if y[2].item() == 1.:
#        print(y)
#        print(output)


#exit()




count = 0
other_count = 0
for x, y in dataset[300:]:
    output = model(x)

    #if output[0].item() > 0.55:
    #    pred = 0
    #elif output[2].item() > 0.25:
    #    pred = 2
    #else:
    #    pred = 1
    
    #print(pred)
    
    pred = torch.argmax(output)

    if y[pred] == 0.:
        #print(str(output) + str(y))
        count += 1
        if(y[1] == 1 or y[2] == 1):
            other_count += 1
            print(output)
        print(str(output) + "|" + str(y))


    #if output.item() > 0.59 and y.item() == 0.:
    #    count += 1
    #elif output.item() <= 0.59 and y.item() == 1.:
    #    count+= 1
    #else:
    #    print(str(output.item()) + "|" + str(y.item()))

print(count)
print(other_count)

tensor([2.2970e-01, 7.7005e-01, 2.4985e-04], grad_fn=<SoftmaxBackward0>)|tensor([1., 0., 0.])
tensor([0.5958, 0.2392, 0.1651], grad_fn=<SoftmaxBackward0>)
tensor([0.5958, 0.2392, 0.1651], grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1.])
tensor([0.0090, 0.6698, 0.3212], grad_fn=<SoftmaxBackward0>)
tensor([0.0090, 0.6698, 0.3212], grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1.])
tensor([4.6771e-04, 9.9218e-01, 7.3520e-03], grad_fn=<SoftmaxBackward0>)
tensor([4.6771e-04, 9.9218e-01, 7.3520e-03], grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1.])
tensor([0.4591, 0.5387, 0.0022], grad_fn=<SoftmaxBackward0>)|tensor([1., 0., 0.])
tensor([9.2266e-01, 7.7324e-02, 1.6183e-05], grad_fn=<SoftmaxBackward0>)
tensor([9.2266e-01, 7.7324e-02, 1.6183e-05], grad_fn=<SoftmaxBackward0>)|tensor([0., 1., 0.])
tensor([0.2256, 0.7735, 0.0009], grad_fn=<SoftmaxBackward0>)|tensor([1., 0., 0.])
tensor([8.5947e-01, 1.4050e-01, 3.4697e-05], grad_fn=<SoftmaxBackward0>)
tensor([8.5947e-01, 1.4050e-01, 3.4697e-05], grad

C:\Users\Antti\AppData\Local\Temp\ipykernel_52420\2662789135.py:28: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(x)


In [23]:
torch.save(model.state_dict(), "model_final.pth")

In [22]:
n_model = NeuralNetwork()
n_model.load_state_dict(torch.load('model2.pth'))

# Put the model in evaluation mode
n_model.eval()

NeuralNetwork(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=3, bias=True)
)

In [26]:
artist, name, _, features = extract.get_current_song()
print(name)
print(features)

output = n_model(features)
pred = torch.argmax(output)
print(pred) # 0 = Neutral, 1, = 




HTTP Error for GET to https://api.spotify.com/v1/me/player/currently-playing with Params: {} returned 401 due to The access token expired


SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/me/player/currently-playing:
 The access token expired, reason: None

In [9]:
count = 0
other_count = 0
for x, y in dataset[300:]:
    output = n_model(x)

    #if output[0].item() > 0.55:
    #    pred = 0
    #elif output[2].item() > 0.25:
    #    pred = 2
    #else:
    #    pred = 1
    
    #print(pred)
    
    pred = torch.argmax(output)

    if y[pred] == 0.:
        #print(str(output) + str(y))
        count += 1
        if(y[1] == 1 or y[2] == 1):
            other_count += 1
        print(str(output) + "|" + str(y))


    #if output.item() > 0.59 and y.item() == 0.:
    #    count += 1
    #elif output.item() <= 0.59 and y.item() == 1.:
    #    count+= 1
    #else:
    #    print(str(output.item()) + "|" + str(y.item()))

print(count)
print(other_count)

tensor([1.1920e-04, 6.0804e-01, 1.5875e-04, 3.9168e-01],
       grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1., 0.])
tensor([8.5327e-02, 9.1268e-01, 1.0813e-04, 1.8866e-03],
       grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1., 0.])
tensor([3.0138e-06, 1.4027e-01, 5.6686e-05, 8.5967e-01],
       grad_fn=<SoftmaxBackward0>)|tensor([0., 1., 0., 0.])
tensor([7.7847e-03, 9.7227e-01, 1.5859e-04, 1.9787e-02],
       grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1., 0.])
tensor([1.3185e-01, 8.6692e-01, 9.6136e-05, 1.1348e-03],
       grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1., 0.])
tensor([1.8690e-03, 9.3012e-01, 1.7924e-04, 6.7830e-02],
       grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 0., 1.])
tensor([9.6059e-02, 9.0197e-01, 1.1382e-04, 1.8542e-03],
       grad_fn=<SoftmaxBackward0>)|tensor([1., 0., 0., 0.])
tensor([2.1571e-02, 9.7783e-01, 7.9497e-05, 5.2248e-04],
       grad_fn=<SoftmaxBackward0>)|tensor([0., 0., 1., 0.])
tensor([1.4925e-03, 9.9273e-01, 1.0641e-04, 5.6697e-03],
       

C:\Users\Antti\AppData\Local\Temp\ipykernel_42348\1103024500.py:28: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(x)
